/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mathcompiler;

public class MathCompiler {
    public static String compile(String input) {
        // actually compile here
        return input;
    }
}
